DECLARE SUB HIT ()
DECLARE SUB MOVE ()
DECLARE SUB ENEMY ()
DECLARE SUB MAKE ()
RANDOMIZE TIMER
SCREEN 13
DIM SHARED CAR.X, CAR.Y, CAR.X.SLOPE, CAR.Y.SLOPE, action$, dir$, ENEMY.X, ENEMY.Y, ENEMY.X.SLOPE, ENEMY.Y.SLOPE
CAR.X = 160
CAR.Y = 100
ENEMY.X = 12
ENEMY.Y = 12

DO
DO
    K$ = INKEY$
    action$ = "draw": MAKE
        FOR SLOW = 1 TO 1000: NEXT SLOW
    action$ = "erase": MAKE
        IF CAR.X <= 10 OR CAR.X >= 310 THEN CAR.X.SLOPE = CAR.X.SLOPE * -1
        IF CAR.Y <= 10 OR CAR.Y >= 190 THEN CAR.Y.SLOPE = CAR.Y.SLOPE * -1
        IF ENEMY.X <= 10 OR ENEMY.X >= 310 THEN ENEMY.X.SLOPE = ENEMY.X.SLOPE * -1: ENEMY.X.SLOPE = ENEMY.X.SLOPE * .4
        IF ENEMY.Y <= 10 OR ENEMY.Y >= 190 THEN ENEMY.Y.SLOPE = ENEMY.Y.SLOPE * -1: ENEMY.X.SLOPE = ENEMY.X.SLOPE * .4

    CAR.X = CAR.X + CAR.X.SLOPE
    CAR.Y = CAR.Y + CAR.Y.SLOPE
    ENEMY.X = ENEMY.X + ENEMY.X.SLOPE
    ENEMY.Y = ENEMY.Y + ENEMY.Y.SLOPE
        IF CAR.X.SLOPE >= 0 THEN CAR.X.SLOPE = CAR.X.SLOPE - .05
        IF CAR.X.SLOPE <= 0 THEN CAR.X.SLOPE = CAR.X.SLOPE + .05
        IF CAR.Y.SLOPE >= 0 THEN CAR.Y.SLOPE = CAR.Y.SLOPE - .05
        IF CAR.Y.SLOPE <= 0 THEN CAR.Y.SLOPE = CAR.Y.SLOPE + .05
        IF ENEMY.X.SLOPE >= 0 THEN ENEMY.X.SLOPE = ENEMY.X.SLOPE - .05
        IF ENEMY.X.SLOPE <= 0 THEN ENEMY.X.SLOPE = ENEMY.X.SLOPE + .05
        IF ENEMY.Y.SLOPE >= 0 THEN ENEMY.Y.SLOPE = ENEMY.Y.SLOPE - .05
        IF ENEMY.Y.SLOPE <= 0 THEN ENEMY.Y.SLOPE = ENEMY.Y.SLOPE + .05
    MOVE
    LOOP WHILE K$ = ""
    Ky = ASC(RIGHT$(K$, 1))
        IF K$ = "8" THEN dir$ = "up"
        IF K$ = "4" THEN dir$ = "left"
        IF K$ = "6" THEN dir$ = "right"
        IF K$ = "2" THEN dir$ = "down"
        IF K$ = "5" THEN dir$ = "brake"
        IF K$ = "-" THEN
            CAR.X = 160
            CAR.Y = 100
            ENEMY.X = 12
            ENEMY.Y = 12
            CAR.X.SLOPE = 0: CAR.Y.SLOPE = 0
            ENEMY.X.SLOPE = 0: ENEMY.Y.SLOPE = 0
        END IF
        IF K$ = "Q" THEN CLS : END

LOOP

SUB MAKE
IF action$ = "erase" THEN
    PAINT (CAR.X, CAR.Y), 0
    PAINT (ENEMY.X, ENEMY.Y), 0
END IF
IF action$ = "draw" THEN
    LINE (CAR.X - 3, CAR.Y - 3)-(CAR.X - 3, CAR.Y + 3), 3
    LINE (CAR.X - 3, CAR.Y + 3)-(CAR.X + 3, CAR.Y + 3), 3
    LINE (CAR.X + 3, CAR.Y + 3)-(CAR.X + 3, CAR.Y - 3), 3
    LINE (CAR.X - 3, CAR.Y - 3)-(CAR.X + 3, CAR.Y - 3), 3
    PAINT (CAR.X, CAR.Y), 3
    LINE (ENEMY.X - 3, ENEMY.Y - 3)-(ENEMY.X - 3, ENEMY.Y + 3), 4
    LINE (ENEMY.X - 3, ENEMY.Y + 3)-(ENEMY.X + 3, ENEMY.Y + 3), 4
    LINE (ENEMY.X + 3, ENEMY.Y + 3)-(ENEMY.X + 3, ENEMY.Y - 3), 4
    LINE (ENEMY.X - 3, ENEMY.Y - 3)-(ENEMY.X + 3, ENEMY.Y - 3), 4
    PAINT (ENEMY.X, ENEMY.Y), 4

END IF

END SUB

SUB MOVE
LOCATE 1, 1: PRINT CAR.X, CAR.Y
LOCATE 2, 1: PRINT ENEMY.X, ENEMY.Y

'*IF THE CARS HIT, MAKE THEM BOUNCE OFF EACH OTHER
'   V2
'V1    V4
'   V3

V1 = (ENEMY.X - 6)
V2 = (ENEMY.Y - 6)
V3 = (ENEMY.Y + 6)
V4 = (ENEMY.X + 6)
IF CAR.X >= V1 AND CAR.Y > V2 AND CAR.X < V4 AND CAR.Y < V3 THEN
   E.X.TMP = ENEMY.X.SLOPE
   E.Y.TMP = ENEMY.Y.SLOPE
   C.X.TMP = CAR.X.SLOPE
   C.Y.TMP = CAR.Y.SLOPE
   IF CAR.X < ENEMY.X AND CAR.Y > V2 AND CAR.Y < V3 THEN CAR.X.SLOPE = E.X.TMP: ENEMY.X.SLOPE = C.X.TMP
   IF CAR.X > ENEMY.X AND CAR.Y > V2 AND CAR.Y < V3 THEN CAR.X.SLOPE = E.X.TMP: ENEMY.X.SLOPE = C.X.TMP
   IF CAR.Y < ENEMY.Y AND CAR.X > V1 AND CAR.X < V4 THEN CAR.Y.SLOPE = E.Y.TMP: ENEMY.Y.SLOPE = C.Y.TMP
   IF CAR.Y > ENEMY.Y AND CAR.X > V1 AND CAR.X < V4 THEN CAR.Y.SLOPE = E.Y.TMP: ENEMY.Y.SLOPE = C.Y.TMP
   BEEP
END IF
'*MOVE THE CAR
IF dir$ = "up" THEN
    CAR.Y.SLOPE = CAR.Y.SLOPE + (-.3)
END IF
IF dir$ = "down" THEN
    CAR.Y.SLOPE = CAR.Y.SLOPE + (.3)
END IF
IF dir$ = "left" THEN
    CAR.X.SLOPE = CAR.X.SLOPE + (-.3)
END IF
IF dir$ = "right" THEN
    CAR.X.SLOPE = CAR.X.SLOPE + (.3)
END IF
IF dir$ = "brake" THEN
IF CAR.X.SLOPE >= .6 THEN CAR.X.SLOPE = CAR.X.SLOPE - .6
IF CAR.X.SLOPE <= -.6 THEN CAR.X.SLOPE = CAR.X.SLOPE + .6
IF CAR.Y.SLOPE >= .6 THEN CAR.Y.SLOPE = CAR.Y.SLOPE - .6
IF CAR.Y.SLOPE <= -.6 THEN CAR.Y.SLOPE = CAR.Y.SLOPE + .6
END IF

IF CAR.X.SLOPE >= 7 THEN CAR.X.SLOPE = 7
IF CAR.X.SLOPE <= -7 THEN CAR.X.SLOPE = -7
IF CAR.Y.SLOPE >= 7 THEN CAR.Y.SLOPE = 7
IF CAR.Y.SLOPE <= -7 THEN CAR.Y.SLOPE = -7

dir$ = ""
'*MOVE THE ENEMY ENEMY
IF ENEMY.X < CAR.X THEN ENEMY.X.SLOPE = ENEMY.X.SLOPE + .1
IF ENEMY.X > CAR.X THEN ENEMY.X.SLOPE = ENEMY.X.SLOPE - .1
IF ENEMY.Y < CAR.Y THEN ENEMY.Y.SLOPE = ENEMY.Y.SLOPE + .1
IF ENEMY.Y > CAR.Y THEN ENEMY.Y.SLOPE = ENEMY.Y.SLOPE - .1

IF ENEMY.X < (CAR.X - 10) AND ENEMY.X > (CAR.X + 10) THEN ENEMY.X.SLOPE = ENEMY.X.SLOPE + .2
IF ENEMY.Y < (CAR.X - 10) AND ENEMY.X > (CAR.X + 10) THEN ENEMY.Y.SLOPE = ENEMY.Y.SLOPE + .2


END SUB

